# Generated by Django 6.0 on 2025-12-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='image/profile/')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('my_projects', models.IntegerField()),
                ('work_experience', models.IntegerField()),
                ('awards_won', models.IntegerField()),
                ('cv', models.FileField(upload_to='file/cv/')),
                ('fb_link', models.URLField()),
                ('twitter_link', models.URLField()),
                ('linkedin_link', models.URLField()),
                ('github_link', models.URLField()),
                ('instagram_link', models.URLField()),
            ],
        ),
    ]
