# Generated by Django 6.0 on 2025-12-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('degree', models.CharField(max_length=100)),
                ('based_in', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('availability', models.CharField(max_length=50)),
            ],
        ),
    ]
