# Generated by Django 6.0 on 2025-12-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description_2',
            field=models.TextField(default='write here'),
        ),
    ]
