# Generated by Django 6.0 on 2025-12-19 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logo',
            old_name='image',
            new_name='logo_image',
        ),
    ]
