# Generated by Django 6.0 on 2025-12-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_image_logo_logo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/logo/'),
        ),
    ]
