# Generated by Django 6.0 on 2025-12-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_logo_logo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_title', models.CharField(max_length=300)),
                ('professional_Journey_title', models.CharField(max_length=300)),
                ('education_title', models.CharField(max_length=300)),
            ],
        ),
    ]
