# Generated by Django 6.0 on 2025-12-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='service_title',
            field=models.CharField(default='Services', max_length=300),
        ),
    ]
