# Generated by Django 6.0 on 2025-12-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_resume_service_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='portfolio_title',
            field=models.CharField(default='Portfolio', max_length=300),
        ),
    ]
