# Generated by Django 6.0 on 2025-12-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_resume_portfolio_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='contact_title',
            field=models.CharField(default='Get in Touch', max_length=300),
        ),
    ]
